package group.rookie.dbservice.entity;

import java.io.Serializable;

public class Article implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_id
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_title
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_subtitle
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    private String articleSubtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_abstract
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    private String articleAbstract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author_id
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.category
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tags
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_id
     *
     * @return the value of article.article_id
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_id
     *
     * @param articleId the value for article.article_id
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_title
     *
     * @return the value of article.article_title
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_title
     *
     * @param articleTitle the value for article.article_title
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_subtitle
     *
     * @return the value of article.article_subtitle
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public String getArticleSubtitle() {
        return articleSubtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_subtitle
     *
     * @param articleSubtitle the value for article.article_subtitle
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public void setArticleSubtitle(String articleSubtitle) {
        this.articleSubtitle = articleSubtitle == null ? null : articleSubtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_abstract
     *
     * @return the value of article.article_abstract
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public String getArticleAbstract() {
        return articleAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_abstract
     *
     * @param articleAbstract the value for article.article_abstract
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public void setArticleAbstract(String articleAbstract) {
        this.articleAbstract = articleAbstract == null ? null : articleAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author_id
     *
     * @return the value of article.author_id
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author_id
     *
     * @param authorId the value for article.author_id
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.category
     *
     * @return the value of article.category
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.category
     *
     * @param category the value for article.category
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tags
     *
     * @return the value of article.tags
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tags
     *
     * @param tags the value for article.tags
     *
     * @mbg.generated Wed Jun 22 19:05:25 CST 2022
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }
}